apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  #minReadySeconds: 30
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
  selector:
    matchLabels:
      app: webapp

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-queue
  labels:
    app: webapp-queue
spec:
  containers:
    - name: webapp-queue
      image: richardchesterwood/k8s-fleetman-queue:release1