apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp
spec:
  replicas: 1
  template:
    metadata:
      name: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
  selector:
    matchLabels:
      app: webapp

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-queue
  labels:
    app: webapp-queue
spec:
  containers:
    - name: webapp-queue
      image: richardchesterwood/k8s-fleetman-queue:release1